{
 "title": "Match Making",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tickets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bytes per Ticket",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_total_bytes_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "99.9%-ile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_total_bytes_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "99%-ile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_total_bytes_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "95%-ile"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_total_bytes_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "90%-ile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_total_bytes_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "50%-ile"
      },
      {
       "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_total_bytes_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "10%-ile"
      }
     ]
    },
    {
     "title": "SearchFields per Ticket",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "99.9%-ile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "99%-ile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "95%-ile"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "90%-ile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "50%-ile"
      },
      {
       "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "10%-ile"
      }
     ]
    },
    {
     "title": "Ticket Assigned/Release Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "rate(openmatch_dev_)", "legendFormat": "99.9%-ile" },
      {
       "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "99%-ile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "95%-ile"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "90%-ile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "50%-ile"
      },
      {
       "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_searchfields_per_ticket_bucket[5m])) by (le))\n",
       "legendFormat": "10%-ile"
      }
     ]
    }
   ]
  },
  {
   "title": "Matches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bytes per Match",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_total_bytes_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "99.9%-ile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_total_bytes_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "99%-ile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_total_bytes_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "95%-ile"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_total_bytes_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "90%-ile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_total_bytes_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "50%-ile"
      },
      {
       "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_total_bytes_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "10%-ile"
      }
     ]
    },
    {
     "title": "Tickets per Match",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_tickets_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "99.9%-ile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_tickets_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "99%-ile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_tickets_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "95%-ile"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_tickets_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "90%-ile"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_tickets_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "50%-ile"
      },
      {
       "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_tickets_per_match_bucket[5m])) by (le))\n",
       "legendFormat": "10%-ile"
      }
     ]
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Query Cache Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openmatch_dev_query_total_cache_items",
     "legendFormat": "Total: {{kubernetes_pod_name}}"
    },
    {
     "expr": "openmatch_dev_query_delta_cache_items",
     "legendFormat": "Delta: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Tickets per Query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_query_tickets_per_query_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Query Cache Waiting Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_query_waiting_requests_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Query Cache Update Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_query_update_latency_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Query Cache Update Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openmatch_dev_query_cache_updates[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Evaluator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Matches per Evaluate Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_evaluator_matches_per_request[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_evaluator_matches_per_request[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_evaluator_matches_per_request[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_evaluator_matches_per_request[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_evaluator_matches_per_request[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_evaluator_matches_per_request[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Matches per Evaluate Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_evaluator_matches_per_response[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_evaluator_matches_per_response[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_evaluator_matches_per_response[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_evaluator_matches_per_response[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_evaluator_matches_per_response[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_evaluator_matches_per_response[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Collided Matches per Evaluate",
   "type": "graph",
   "description": "Only applies when using the default evaluator",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_evaluator_collided_matches_per_call[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_evaluator_collided_matches_per_call[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_evaluator_collided_matches_per_call[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_evaluator_collided_matches_per_call[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_evaluator_collided_matches_per_call[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_evaluator_collided_matches_per_call[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  { "title": "Synchronizer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Synchronizer Registration MMF Done Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_synchronizer_registration_mmf_done_time_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Synchronizer Registration Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_synchronizer_registration_wait_time_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  },
  {
   "title": "Synchronizer Iteration Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(openmatch_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99.9%-ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openmatch_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "99%-ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(openmatch_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "95%-ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openmatch_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "90%-ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(openmatch_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "50%-ile"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(openmatch_dev_synchronizer_iteration_latency_bucket[5m])) by (le))\n",
     "legendFormat": "10%-ile"
    }
   ]
  }
 ]
}